// <auto-generated />
using System;
using AasDemoapp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AasDemoapp.Migrations
{
    [DbContext(typeof(AasDemoappContext))]
    [Migration("20240215064642_Refac5")]
    partial class Refac5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("KatalogEintragId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KatalogEintragId");

                    b.ToTable("ConfiguredProducts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ImportedShell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteRegistryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportedShells");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.KatalogEintrag", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("KatalogEintragTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalAasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReferencedTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferencedTypeId");

                    b.ToTable("KatalogEintraege");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ProducedProduct", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfiguredProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredProductId");

                    b.ToTable("ProducedProducts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ProductPart", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ConfiguredProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("KatalogEintragId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<long?>("ProducedProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredProductId");

                    b.HasIndex("KatalogEintragId");

                    b.HasIndex("ProducedProductId");

                    b.ToTable("ProductParts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.Setting", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.Supplier", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.UpdateableShell", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("KatalogEintragId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateFoundTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KatalogEintragId");

                    b.ToTable("UpdateableShells");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", null)
                        .WithMany("ConfiguredProducts")
                        .HasForeignKey("KatalogEintragId");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.KatalogEintrag", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", "ReferencedType")
                        .WithMany()
                        .HasForeignKey("ReferencedTypeId");

                    b.Navigation("ReferencedType");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ProducedProduct", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.ConfiguredProduct", "ConfiguredProduct")
                        .WithMany("ProducedProducts")
                        .HasForeignKey("ConfiguredProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ConfiguredProduct");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ProductPart", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.ConfiguredProduct", "ConfiguredProduct")
                        .WithMany("Bestandteile")
                        .HasForeignKey("ConfiguredProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", "Bestandteil")
                        .WithMany()
                        .HasForeignKey("KatalogEintragId");

                    b.HasOne("AasDemoapp.Database.Model.ProducedProduct", "ProducedProduct")
                        .WithMany("Bestandteile")
                        .HasForeignKey("ProducedProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bestandteil");

                    b.Navigation("ConfiguredProduct");

                    b.Navigation("ProducedProduct");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.UpdateableShell", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", "KatalogEintrag")
                        .WithMany()
                        .HasForeignKey("KatalogEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KatalogEintrag");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.Navigation("Bestandteile");

                    b.Navigation("ProducedProducts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.KatalogEintrag", b =>
                {
                    b.Navigation("ConfiguredProducts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ProducedProduct", b =>
                {
                    b.Navigation("Bestandteile");
                });
#pragma warning restore 612, 618
        }
    }
}
