// <auto-generated />
using System;
using AasDemoapp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AasDemoapp.Migrations
{
    [DbContext(typeof(AasDemoappContext))]
    [Migration("20240214090301_Refac")]
    partial class Refac
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("KatalogEintragTypId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KatalogEintragTypId");

                    b.ToTable("ConfiguredProducts");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ImportedShell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteRegistryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportedShells");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.KatalogEintrag", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ConfiguredProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("KatalogEintragTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReferencedTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredProductId");

                    b.HasIndex("ReferencedTypeId");

                    b.ToTable("KatalogEintraege");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.Setting", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.Supplier", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", "KatalogEintragTyp")
                        .WithMany()
                        .HasForeignKey("KatalogEintragTypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KatalogEintragTyp");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.KatalogEintrag", b =>
                {
                    b.HasOne("AasDemoapp.Database.Model.ConfiguredProduct", null)
                        .WithMany("Bestandteile")
                        .HasForeignKey("ConfiguredProductId");

                    b.HasOne("AasDemoapp.Database.Model.KatalogEintrag", "ReferencedType")
                        .WithMany()
                        .HasForeignKey("ReferencedTypeId");

                    b.Navigation("ReferencedType");
                });

            modelBuilder.Entity("AasDemoapp.Database.Model.ConfiguredProduct", b =>
                {
                    b.Navigation("Bestandteile");
                });
#pragma warning restore 612, 618
        }
    }
}
